# Generated by Django 4.2 on 2024-08-15 19:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_cyclist', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_cyclist.accessories')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_cyclist.order')),
            ],
            options={
                'unique_together': {('order', 'accessories')},
            },
        ),
        migrations.CreateModel(
            name='OrderBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_cyclist.bike')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_cyclist.order')),
            ],
            options={
                'unique_together': {('order', 'bike')},
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_card',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El número de cédula debe tener 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener entre 7 y 15 dígitos.', regex='^\\d{7,15}$')]),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='order',
            name='accessories',
            field=models.ManyToManyField(through='city_cyclist.OrderAccessories', to='city_cyclist.accessories'),
        ),
        migrations.AddField(
            model_name='order',
            name='bikes',
            field=models.ManyToManyField(through='city_cyclist.OrderBike', to='city_cyclist.bike'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='city_cyclist.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='method_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_cyclist.paymenttype'),
        ),
    ]
